apiVersion: 1

notifiers:
  - name: Email Alerts
    type: email
    uid: email_notifications
    org_id: 1
    is_default: true
    settings:
      addresses: ${GRAFANA_ALERT_EMAIL_ADDRESSES}

  - name: Slack Alerts
    type: slack
    uid: slack_notifications
    org_id: 1
    is_default: false
    settings:
      url: ${GRAFANA_ALERT_SLACK_WEBHOOK}
      recipient: "#alerts-procurement-portal"